import "./globals.css";

export const metadata = {
  title: "the margins | fragments of thoughts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
      <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
      <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
      <link rel="manifest" href="/site.webmanifest"></link>
      <body
        className='min-h-screen w-full max-w-6xl mx-auto py-32 antialiased'
      >
        {children}
      </body>
    </html>
  );
}
